name: worflow-pullrequest
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Validar el repositorio
        uses: actions/checkout@v3
